base_uri = "https://www.imdb.com/"

search_imdb_id = {"title": '%sfind?q=%s%s' % (base_uri, "%s", "&s=tt&ref_=fn_al_tt_mr"),
                  "person": '%sfind?q=%s%s' % (base_uri, "%s", "&s=nm&ref_=fn_al_nm_mr"),
                  "company": '%sfind?q=%s%s' % (base_uri, "%s", "&s=co&ref_=fn_al_co_mr"),
                  "character": '%sfind?q=%s%s' % (base_uri, "%s", "&s=ch&ref_=fn_al_ch_mr"),
                  "event": '%sfind?q=%s%s' % (base_uri, "%s", "&s=ev&ref_=fn_al_ev_mr"),
                  "news": '%sfind?q=%s%s' % (base_uri, "%s", "&s=ni&ref_=fn_al_ni_mr")}

imdb_uris = {"title": "%stitle/%s" % (base_uri, "%s"),
             "plotsummary": "%stitle/%s/plotsummary" % (base_uri, "%s"),
             "keywords": "%stitle/%s/keywords" % (base_uri, "%s"),
             "fullcredits": "%stitle/%s/fullcredits" % (base_uri, "%s"),
             "companycredits": "%stitle/%s/companycredits" % (base_uri, "%s"),
             "taglines": "%stitle/%s/taglines" % (base_uri, "%s"),
             "releaseinfo": "%stitle/%s/releaseinfo" % (base_uri, "%s"),
             "year": "%stitle/?year=%s&explore=title_type,genres" % (base_uri, "%s"),
             "region": "%scalendar/?region=%s" % (base_uri, "%s"),
             "externalreviews": "%stitle/%s/externalreviews" % (base_uri, "%s"),
             "reviews": "%stitle/%s/reviews" % (base_uri, "%s"),
             "spoiler_reviews": "%stitle/%s/reviews?spoiler=hide&sort=helpfulnessScore&dir=desc&ratingFilter=0" % (base_uri, "%s"),
             "externalsites": "%stitle/%s/externalsites" % (base_uri, "%s"),
             "parentalguide": "%stitle/%s/parentalguide" % (base_uri, "%s"),
             "technical": "%stitle/%s/technical" % (base_uri, "%s"),
             "ratings": "%stitle/%s/ratings" % (base_uri, "%s"),
             "criticreviews": "%stitle/%s/criticreviews" % (base_uri, "%s"),
             "calendar": "%scalendar" % base_uri,
             "top": "%schart/top" % base_uri,
             "top-english-movies": "%schart/top-english-movies" % base_uri,
             "boxoffice": "%schart/boxoffice" % base_uri,
             "moviemeter": "%schart/moviemeter" % base_uri,
             "bottom": "%schart/bottom" % base_uri,
             "toptv": "%schart/toptv" % base_uri,
             "tvmeter": "%schart/tvmeter" % base_uri,
             "top-rated-indian-movies": "%sindia/top-rated-indian-movies" % base_uri,
             "top-rated-tamil-movies": "%sindia/top-rated-tamil-movies" % base_uri,
             "top-rated-telugu-movies": "%sindia/top-rated-telugu-movies" % base_uri,
             "top-rated-malayalam-movies": "%sindia/top-rated-malayalam-movies" % base_uri,
             "upcoming": "%sindia/upcoming" % base_uri,
             "tamil": "%sindia/tamil" % base_uri,
             "telugu": "%sindia/telugu" % base_uri,
             "released": "%sindia/released" % base_uri,
             "global": "%sindia/global" % base_uri,
             "hindi": "%sindia/hindi" % base_uri}

tag_search = {"popularity": """
            Popularity
            """,
              "official": '#official',
              "miscellaneous": "#misc",
              "photo": "#photos",
              "videos": "#videos",
              "production": '#production',
              "distributor": '#distributors',
              "special_effects": '#specialEffects',
              "other": "#other",
              "writer": "writing",
              "director": "directed",
              "producer": "produced",
              "cast": "cast",
              "music": "music",
              "cinematography": "cinematography",
              "production design": "production design",
              "film editing": "film editing",
              "casting": "casting",
              "certificates": "#certificates",
              "advisory-nudity": "#advisory-nudity",
              "advisory-violence": "#advisory-violence",
              "advisory-profanity": "#advisory-profanity",
              "advisory-alcohol": "#advisory-alcohol",
              "advisory-frightening": "#advisory-frightening",
              "advisory-spoilers": "#advisory-spoilers",
              'mpaa': 'tr[id="mpaa-rating"]',
              'certifications': 'tr[id="certifications-list"]',
              'nudity': 'div[data-category="nudity"]',
              'violence': 'div[data-category="violence"]',
              "profanity": 'div[data-category="profanity"]',
              'alcohol': 'div[data-category="alcohol"]',
              'frightening': 'div[data-category="frightening"]',
              "runtime": "runtime",
              'sound mix': 'sound mix',
              'color': 'color',
              'aspect ratio': 'aspect ratio',
              'camera': 'camera',
              'laboratory': 'laboratory',
              'negative format': 'negative format',
              'cinematographic process': 'cinematographic process',
              'printed film format': 'printed film format',
              'film length': 'film length',
              'rating_demo': 'Rating By Demographic'}
